apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-master
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: java-app-master
  template:
    metadata:
      labels:
        app: java-app-master
    spec:
      containers:
        - name: java-app-master
          image: hamritha817/devsecops:14
          ports:
            - containerPort: 8083  # Adjust the container port as needed
