apiVersion: v1
kind: Service
metadata:
  name: java-app-master
spec:
  selector:
    app: java-app-master
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30001
