apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: my-app
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
