apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  selector:
    app: java-app
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
