apiVersion: v1
kind: Service
metadata:
  name: java-app-qa
  namespace: qa
spec:
  selector:
    app: java-app-qa
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30001
